### ISSUE TITLE
How many input images did you use to learn?

### ISSUE THREAD

**Issue by chartgod** [TheXirex/Airbus-Ship-Segmentation#1]
How many input images did you use to learn?

**Comment by TheXirex** [comment]
You can setup the data specified in the readme-file, then run the [train.py](https://github.com/TheXirex/Airbus-Ship-Segmentation/blob/main/train.py) file, specifically this [piece of code](https://github.com/TheXirex/Airbus-Ship-Segmentation/blob/10ae79778b6ff1f97f145bf99740033b7544ec04/train.py#L18C1-L35C58) and print the size of the training dataframe.

**Comment by chartgod** [comment]
Thx
